"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-str' references
in its source tree. Two outcomes:

- Module installed AND import succeeds → test PASSES.
- Module installed BUT import fails (e.g. internal rename like
  `scitex_io._load_cache` → `scitex_io._loading._load_cache`) →
  test FAILS loudly.
- Module NOT installed (peer standalone absent in the CI env) →
  test is SKIPPED via `pytest.importorskip`. The umbrella's CI
  (which installs every peer) catches cross-package renames.
"""

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    "scitex_dev",
    "scitex_dict",
    "scitex_logging",
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import_resolves_module_name(module_name):
    """Importing scitex-str's declared cross-package dependency must yield a module object."""
    # Arrange
    name = module_name
    # Act
    module = pytest.importorskip(name)
    # Assert
    assert module is not None


def test_cross_package_imports_list_is_iterable_sequence():
    """The CROSS_PACKAGE_IMPORTS constant is a list (the gate has a schema)."""
    # Arrange
    declared = CROSS_PACKAGE_IMPORTS
    # Act
    is_list = isinstance(declared, list)
    # Assert
    assert is_list is True
